<?php

/**
 *
 * AUTOMATICALLY GENERATED CODE - DO NOT EDIT BY HAND
 *
**/
define('PLUGIN_TEST4WEB_TITLE', "Web Test using TestGen4Web and Simpletest");
define('PLUGIN_TEST4WEB_DESCRIPTION', "Enables generation of an HTTP web test using TestGen4Web and Simpletest PHP");
define('PLUGIN_TEST4WEB_PROXY_USER_DESCRIPTION', "Proxy username");
define('PLUGIN_TEST4WEB_PROXY_PASSWORD_DESCRIPTION', "Proxy password");
define('PLUGIN_TEST4WEB_PROXY_HOST_DESCRIPTION', "URL of http proxy host (i.e. http://localhost:8080/)");
define('PLUGIN_TEST4WEB_XML_DESCRIPTION', "The XML generated by TestGen4Web Replace in the code the username and password of the identity with  and");
define('PLUGIN_TEST4WEB_RULE_5_0', "The XML is required");
define('PLUGIN_TEST4WEB_TYPE', "Choose the output to report");
define('PLUGIN_TEST4WEB_DETAILS', "Detailed report");
define('PLUGIN_TEST4WEB_ONLY_TIME', "Only elapsed time");
define('PLUGIN_TEST4WEB_THRESHOLD_DESCRIPTION', "Timeout for navigation test in seconds (Leave zero for the maximum)");
define('PLUGIN_TEST4WEB_RULE_7_0', "Timeout is required");
define('PLUGIN_TEST4WEB_RULE_7_1', "Timeout must be a number");

?>